name = "trifrost_website"
main = "src/index.ts"
account_id = "caecd57a23368bcaa309d412bee35b5f"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public/"
binding = "ASSETS"

[vars]
TRIFROST_NAME='TriFrost_Website'
TRIFROST_VERSION='1.0.0'

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

[[durable_objects.bindings]]
name = "MainDurable"
class_name = "TriFrostDurableObject"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["TriFrostDurableObject"]

[[r2_buckets]]
binding = "TRIFROST_BUCKET"
bucket_name = "trifrost-r2-eu"
preview_bucket_name = "trifrost-r2-eu"
jurisdiction = "eu"
